### ISSUE TITLE
Getting / setting empty cells?

### ISSUE THREAD

**Issue by nixsy** [magnetikonline/phpgooglespreadsheetapi#2]
Is there a way to set the value of an empty cell?  So far, I could only get a cell with getWorksheetCellList(), but that does not return empty cells, even if they are within the specified range.

**Comment by magnetikonline** [comment]
Hello @nixsy, yeah haven't touched this code in a while. From memory this was a problem/limitation of the API at Google's end (at least at time of development).

You could fetch/modify existing cells - but adding a new cell is a little harder. From memory where was an API method to poke individual cells with data. You would have to dig through the Google API documentation to find this.
