### ISSUE TITLE
tokendata not save in .tokendata file.

### ISSUE THREAD

**Issue by nu1ww** [magnetikonline/phpgooglespreadsheetapi#3]
I've try to exchange tokens data using exchangecodefortokens.php with the code. its not working. after execute exchangecodefortokens.php file this message appear on page  "Usage: exchangecodefortokens.php -c AUTHORIZATION CODE"   what should i do now ?

**Comment by magnetikonline** [comment]
Did you follow everything in the **Setup** step?

https://github.com/magnetikonline/phpgooglespreadsheetapi#setup

You need to create a new Google OAuth client token via the web, edit `config.php` to suit - and then call `buildrequesturl.php`. The URL returned here is then put into another browser - upon it's return you use the `code=` querystring value for the argument to `exchangecodefortokens.php`.

Note - all these scripts need to be called from the CLI - _not_ a browser window.
