### ISSUE TITLE
Add new rows or cells

### ISSUE THREAD

**Issue by jberlana** [magnetikonline/phpgooglespreadsheetapi#4]
Hi, first of all said that you have done a great job here. 
But, How can I add new cells to a worksheet?

**Comment by magnetikonline** [comment]
Hello @jberlana - sorry for the late reply.

You can't add cells - the Google Spreadsheet API does not allow it - only updates.

This pull request (which I will merge at some point) - gives access to the poorly-documented add row method - which is probably the best you can do.

https://github.com/magnetikonline/phpgooglespreadsheetapi/pull/1

 Pete
