### ISSUE TITLE
Undefined variable error

### ISSUE THREAD

**Issue by adriweb** [magnetikonline/phpgooglespreadsheetapi#6]
in [api.php](https://github.com/magnetikonline/phpgooglespreadsheetapi/blob/master/googlespreadsheet/api.php#L334), in `updateWorksheetCellList`, there needs to be a `$cellItem = false;` declaration before the while loop, otherwise the `if ($cellItem === false)` crashes when `$cellItem` has not been defined, which happens when `$worksheetCellList` is empty.
A PR just for that seemed a bit too much...

**Comment by magnetikonline** [comment]
Thanks @adriweb - I'll get to this when time allows.

**Comment by magnetikonline** [comment]
Finally squashed this in c6fd599 - thanks again @adriweb :+1:
