### ISSUE TITLE
config file issue.

### ISSUE THREAD

**Issue by jvh1** [magnetikonline/phpgooglespreadsheetapi#7]
Hello, I have implemented the code and here is the url: http://wecho256.com/2609_back/new/example.php

When run the url then "Error: unable to locate token file [.tokendata] " issue is appearing. 

Can you please tell me what i will mention on "tokenDataFile" parameter on config.php file. Please tell me in details to solve the issue.

Regards.

**Comment by magnetikonline** [comment]
Hello @jvh1 - you need to follow the steps under the example section here: https://github.com/magnetikonline/phpgooglespreadsheetapi#example This will create the config and OAuth2 credentials needed.

Also, this script is intended for CLI/command line use - not from Apache/PHP-FPM/etc.

 Pete

**Comment by jvh1** [comment]
Hello, Thanks for your reply. We can't use the script on apache server.

Regards.

**Comment by magnetikonline** [comment]
@jvh1 sorry - maybe not being clear - the script is for CLI **only** not from a HTTP web server.
