### ISSUE TITLE
Little adjustment for 1st timers in README

### ISSUE THREAD

**Issue by jijzult** [magnetikonline/phpgooglespreadsheetapi#8]
Please specify/modify for the first timers under the section Setup:

After accepting terms you will be taken back to the entered redirect URI along with a ?code= querystring value. Use the code in between '?code=' and '#'.

**Comment by magnetikonline** [comment]
Thanks for the feedback! Will add this in.

**Comment by magnetikonline** [comment]
Better late than never - fixed in 21bfbab.
